apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-deployment2

  labels:

    app: nginx

spec:

  replicas: 1

  selector:

    matchLabels:

      app: nginx

  template:

    metadata:

      labels:

        app: nginx

    spec:

      containers:

      - name: nginx2

        image: public.ecr.aws/o5n4a2g6/nginx1:v2

        ports:

        - containerPort: 80
